### ISSUE TITLE
Can't build with GHC 8.2

### ISSUE THREAD

**Issue by RyanGlScott** [khibino/haskell-th-data-compat#1]
GHC 8.2 (`template-haskell-2.12.0.0`) introduces `DerivingStrategies`, and with that change came modifications to some Tempate Haskell constructors. For instance, we [now have](http://git.haskell.org/ghc.git/blob/ff363bd74c8b2505b92b39d5fedcf95b8ab7365a:/libraries/template-haskell/Language/Haskell/TH/Syntax.hs#l1617):

```haskell
DataD Cxt Name [TyVarBndr] (Maybe Kind) [Con] [DerivClause]
```

instead of:

```haskell
DataD Cxt Name [TyVarBndr] (Maybe Kind) [Con] Cxt
```

This causes `th-data-compat` to fail to build with GHC 8.2.1-rc2:

```
[1 of 2] Compiling Language.Haskell.TH.Compat.Data.Current ( src/Language/Haskell/TH/Compat/Data/Current.hs, dist/dist-sandbox-1069cc36/build/Language/Haskell/TH/Compat/Data/Current.o )

src/Language/Haskell/TH/Compat/Data/Current.hs:20:53: error:
    • Couldn't match type ‘Language.Haskell.TH.Syntax.Q’ with ‘[]’
      Expected type: [Language.Haskell.TH.Lib.DerivClauseQ]
        Actual type: Language.Haskell.TH.Syntax.Q [Type]
    • In the second argument of ‘($)’, namely ‘mapM conT ds’
      In the expression: dataD cxt n bs Nothing cs $ mapM conT ds
      In an equation for ‘dataD'’:
          dataD' cxt n bs cs ds = dataD cxt n bs Nothing cs $ mapM conT ds
   |
20 | dataD' cxt n bs cs ds = dataD cxt n bs Nothing cs $ mapM conT ds
   |                                                     ^^^^^^^^^^^^

src/Language/Haskell/TH/Compat/Data/Current.hs:24:37: error:
    • Couldn't match type ‘Language.Haskell.TH.Syntax.DerivClause’
                     with ‘Type’
      Expected type: Maybe
                       (Cxt, Name, [TyVarBndr], Maybe Kind, [Con], [Type])
        Actual type: Maybe
                       (Cxt, Name, [TyVarBndr], Maybe Kind, [Con],
                        [Language.Haskell.TH.Syntax.DerivClause])
    • In the expression: Just (cxt, n, bs, mk, cs, ds)
      In an equation for ‘unDataD’:
          unDataD (DataD cxt n bs mk cs ds) = Just (cxt, n, bs, mk, cs, ds)
   |
24 | unDataD (DataD cxt n bs mk cs ds) = Just (cxt, n, bs, mk, cs, ds)
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/TH/Compat/Data/Current.hs:31:57: error:
    • Couldn't match type ‘Language.Haskell.TH.Syntax.Q’ with ‘[]’
      Expected type: [Language.Haskell.TH.Lib.DerivClauseQ]
        Actual type: Language.Haskell.TH.Syntax.Q [Type]
    • In the second argument of ‘($)’, namely ‘mapM conT ds’
      In the expression: newtypeD cxt n bs Nothing c $ mapM conT ds
      In an equation for ‘newtypeD'’:
          newtypeD' cxt n bs c ds
            = newtypeD cxt n bs Nothing c $ mapM conT ds
   |
31 | newtypeD' cxt n bs c ds = newtypeD cxt n bs Nothing c $ mapM conT ds
   |                                                         ^^^^^^^^^^^^

src/Language/Haskell/TH/Compat/Data/Current.hs:35:42: error:
    • Couldn't match type ‘Language.Haskell.TH.Syntax.DerivClause’
                     with ‘Type’
      Expected type: Maybe
                       (Cxt, Name, [TyVarBndr], Maybe Kind, Con, [Type])
        Actual type: Maybe
                       (Cxt, Name, [TyVarBndr], Maybe Kind, Con,
                        [Language.Haskell.TH.Syntax.DerivClause])
    • In the expression: Just (cxt, n, bs, mk, c, ds)
      In an equation for ‘unNewtypeD’:
          unNewtypeD (NewtypeD cxt n bs mk c ds)
            = Just (cxt, n, bs, mk, c, ds)
   |
35 | unNewtypeD (NewtypeD cxt n bs mk c ds) = Just (cxt, n, bs, mk, c, ds)
   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/TH/Compat/Data/Current.hs:42:61: error:
    • Couldn't match type ‘Language.Haskell.TH.Syntax.Q’ with ‘[]’
      Expected type: [Language.Haskell.TH.Lib.DerivClauseQ]
        Actual type: Language.Haskell.TH.Syntax.Q [Type]
    • In the second argument of ‘($)’, namely ‘mapM conT ds’
      In the expression: dataInstD cxt n as Nothing cs $ mapM conT ds
      In an equation for ‘dataInstD'’:
          dataInstD' cxt n as cs ds
            = dataInstD cxt n as Nothing cs $ mapM conT ds
   |
42 | dataInstD' cxt n as cs ds = dataInstD cxt n as Nothing cs $ mapM conT ds
   |                                                             ^^^^^^^^^^^^

src/Language/Haskell/TH/Compat/Data/Current.hs:46:45: error:
    • Couldn't match type ‘Language.Haskell.TH.Syntax.DerivClause’
                     with ‘Type’
      Expected type: Maybe (Cxt, Name, [Type], Maybe Kind, [Con], [Type])
        Actual type: Maybe
                       (Cxt, Name, [Type], Maybe Kind, [Con],
                        [Language.Haskell.TH.Syntax.DerivClause])
    • In the expression: Just (cxt, n, as, mk, cs, ds)
      In an equation for ‘unDataInstD’:
          unDataInstD (DataInstD cxt n as mk cs ds)
            = Just (cxt, n, as, mk, cs, ds)
   |
46 | unDataInstD (DataInstD cxt n as mk cs ds) = Just (cxt, n, as, mk, cs, ds)
   |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/TH/Compat/Data/Current.hs:53:65: error:
    • Couldn't match type ‘Language.Haskell.TH.Syntax.Q’ with ‘[]’
      Expected type: [Language.Haskell.TH.Lib.DerivClauseQ]
        Actual type: Language.Haskell.TH.Syntax.Q [Type]
    • In the second argument of ‘($)’, namely ‘mapM conT ds’
      In the expression: newtypeInstD cxt n as Nothing c $ mapM conT ds
      In an equation for ‘newtypeInstD'’:
          newtypeInstD' cxt n as c ds
            = newtypeInstD cxt n as Nothing c $ mapM conT ds
   |
53 | newtypeInstD' cxt n as c ds = newtypeInstD cxt n as Nothing c $ mapM conT ds
   |                                                                 ^^^^^^^^^^^^

src/Language/Haskell/TH/Compat/Data/Current.hs:57:50: error:
    • Couldn't match type ‘Language.Haskell.TH.Syntax.DerivClause’
                     with ‘Type’
      Expected type: Maybe (Cxt, Name, [Type], Maybe Kind, Con, [Type])
        Actual type: Maybe
                       (Cxt, Name, [Type], Maybe Kind, Con,
                        [Language.Haskell.TH.Syntax.DerivClause])
    • In the expression: Just (cxt, n, as, mk, c, ds)
      In an equation for ‘unNewtypeInstD’:
          unNewtypeInstD (NewtypeInstD cxt n as mk c ds)
            = Just (cxt, n, as, mk, c, ds)
   |
57 | unNewtypeInstD (NewtypeInstD cxt n as mk c ds) = Just (cxt, n, as, mk, c, ds)
   |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by RyanGlScott** [comment]
Fixed in f2820259d57391e3cc0b1792c220ffd5df94db7f.
